//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminClient.QueueServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Branch", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Branch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((this.BranchIdField.Equals(value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvgDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvgDuration {
            get {
                return this.AvgDurationField;
            }
            set {
                if ((this.AvgDurationField.Equals(value) != true)) {
                    this.AvgDurationField = value;
                    this.RaisePropertyChanged("AvgDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((this.BranchIdField.Equals(value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceId {
            get {
                return this.ServiceIdField;
            }
            set {
                if ((this.ServiceIdField.Equals(value) != true)) {
                    this.ServiceIdField = value;
                    this.RaisePropertyChanged("ServiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueueTicket", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class QueueTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BranchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CalledAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompletedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ServiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TicketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TicketNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchId {
            get {
                return this.BranchIdField;
            }
            set {
                if ((this.BranchIdField.Equals(value) != true)) {
                    this.BranchIdField = value;
                    this.RaisePropertyChanged("BranchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CalledAt {
            get {
                return this.CalledAtField;
            }
            set {
                if ((this.CalledAtField.Equals(value) != true)) {
                    this.CalledAtField = value;
                    this.RaisePropertyChanged("CalledAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedAt {
            get {
                return this.CompletedAtField;
            }
            set {
                if ((this.CompletedAtField.Equals(value) != true)) {
                    this.CompletedAtField = value;
                    this.RaisePropertyChanged("CompletedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceId {
            get {
                return this.ServiceIdField;
            }
            set {
                if ((this.ServiceIdField.Equals(value) != true)) {
                    this.ServiceIdField = value;
                    this.RaisePropertyChanged("ServiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketId {
            get {
                return this.TicketIdField;
            }
            set {
                if ((this.TicketIdField.Equals(value) != true)) {
                    this.TicketIdField = value;
                    this.RaisePropertyChanged("TicketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketNumber {
            get {
                return this.TicketNumberField;
            }
            set {
                if ((this.TicketNumberField.Equals(value) != true)) {
                    this.TicketNumberField = value;
                    this.RaisePropertyChanged("TicketNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLog", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class CallLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CalledAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CalledByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TicketIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CalledAt {
            get {
                return this.CalledAtField;
            }
            set {
                if ((this.CalledAtField.Equals(value) != true)) {
                    this.CalledAtField = value;
                    this.RaisePropertyChanged("CalledAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CalledBy {
            get {
                return this.CalledByField;
            }
            set {
                if ((this.CalledByField.Equals(value) != true)) {
                    this.CalledByField = value;
                    this.RaisePropertyChanged("CalledBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogId {
            get {
                return this.LogIdField;
            }
            set {
                if ((this.LogIdField.Equals(value) != true)) {
                    this.LogIdField = value;
                    this.RaisePropertyChanged("LogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TicketId {
            get {
                return this.TicketIdField;
            }
            set {
                if ((this.TicketIdField.Equals(value) != true)) {
                    this.TicketIdField = value;
                    this.RaisePropertyChanged("TicketId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueueServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        AdminClient.QueueServiceRef.User Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.User> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        void Register(AdminClient.QueueServiceRef.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(AdminClient.QueueServiceRef.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBranches", ReplyAction="http://tempuri.org/IService1/GetAllBranchesResponse")]
        AdminClient.QueueServiceRef.Branch[] GetAllBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBranches", ReplyAction="http://tempuri.org/IService1/GetAllBranchesResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.Branch[]> GetAllBranchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBranch", ReplyAction="http://tempuri.org/IService1/AddBranchResponse")]
        void AddBranch(AdminClient.QueueServiceRef.Branch b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBranch", ReplyAction="http://tempuri.org/IService1/AddBranchResponse")]
        System.Threading.Tasks.Task AddBranchAsync(AdminClient.QueueServiceRef.Branch b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBranch", ReplyAction="http://tempuri.org/IService1/UpdateBranchResponse")]
        void UpdateBranch(AdminClient.QueueServiceRef.Branch b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBranch", ReplyAction="http://tempuri.org/IService1/UpdateBranchResponse")]
        System.Threading.Tasks.Task UpdateBranchAsync(AdminClient.QueueServiceRef.Branch b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBranch", ReplyAction="http://tempuri.org/IService1/DeleteBranchResponse")]
        void DeleteBranch(int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteBranch", ReplyAction="http://tempuri.org/IService1/DeleteBranchResponse")]
        System.Threading.Tasks.Task DeleteBranchAsync(int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllServices", ReplyAction="http://tempuri.org/IService1/GetAllServicesResponse")]
        AdminClient.QueueServiceRef.Service[] GetAllServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllServices", ReplyAction="http://tempuri.org/IService1/GetAllServicesResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.Service[]> GetAllServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServicesByBranch", ReplyAction="http://tempuri.org/IService1/GetServicesByBranchResponse")]
        AdminClient.QueueServiceRef.Service[] GetServicesByBranch(int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetServicesByBranch", ReplyAction="http://tempuri.org/IService1/GetServicesByBranchResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.Service[]> GetServicesByBranchAsync(int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddService", ReplyAction="http://tempuri.org/IService1/AddServiceResponse")]
        void AddService(AdminClient.QueueServiceRef.Service s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddService", ReplyAction="http://tempuri.org/IService1/AddServiceResponse")]
        System.Threading.Tasks.Task AddServiceAsync(AdminClient.QueueServiceRef.Service s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateService", ReplyAction="http://tempuri.org/IService1/UpdateServiceResponse")]
        void UpdateService(AdminClient.QueueServiceRef.Service s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateService", ReplyAction="http://tempuri.org/IService1/UpdateServiceResponse")]
        System.Threading.Tasks.Task UpdateServiceAsync(AdminClient.QueueServiceRef.Service s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteService", ReplyAction="http://tempuri.org/IService1/DeleteServiceResponse")]
        void DeleteService(int serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteService", ReplyAction="http://tempuri.org/IService1/DeleteServiceResponse")]
        System.Threading.Tasks.Task DeleteServiceAsync(int serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        AdminClient.QueueServiceRef.User[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllUsers", ReplyAction="http://tempuri.org/IService1/GetAllUsersResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.User[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        AdminClient.QueueServiceRef.User GetUserById(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserById", ReplyAction="http://tempuri.org/IService1/GetUserByIdResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.User> GetUserByIdAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        void AddUser(AdminClient.QueueServiceRef.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(AdminClient.QueueServiceRef.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        void UpdateUser(AdminClient.QueueServiceRef.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(AdminClient.QueueServiceRef.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TakeTicket", ReplyAction="http://tempuri.org/IService1/TakeTicketResponse")]
        AdminClient.QueueServiceRef.QueueTicket TakeTicket(int userId, int serviceId, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TakeTicket", ReplyAction="http://tempuri.org/IService1/TakeTicketResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket> TakeTicketAsync(int userId, int serviceId, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActiveTicketByUser", ReplyAction="http://tempuri.org/IService1/GetActiveTicketByUserResponse")]
        AdminClient.QueueServiceRef.QueueTicket GetActiveTicketByUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetActiveTicketByUser", ReplyAction="http://tempuri.org/IService1/GetActiveTicketByUserResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket> GetActiveTicketByUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicketsByBranch", ReplyAction="http://tempuri.org/IService1/GetTicketsByBranchResponse")]
        AdminClient.QueueServiceRef.QueueTicket[] GetTicketsByBranch(int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicketsByBranch", ReplyAction="http://tempuri.org/IService1/GetTicketsByBranchResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket[]> GetTicketsByBranchAsync(int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWaitingTickets", ReplyAction="http://tempuri.org/IService1/GetWaitingTicketsResponse")]
        AdminClient.QueueServiceRef.QueueTicket[] GetWaitingTickets(int branchId, int serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWaitingTickets", ReplyAction="http://tempuri.org/IService1/GetWaitingTicketsResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket[]> GetWaitingTicketsAsync(int branchId, int serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPositionInQueue", ReplyAction="http://tempuri.org/IService1/GetPositionInQueueResponse")]
        int GetPositionInQueue(int ticketId, int branchId, int serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPositionInQueue", ReplyAction="http://tempuri.org/IService1/GetPositionInQueueResponse")]
        System.Threading.Tasks.Task<int> GetPositionInQueueAsync(int ticketId, int branchId, int serviceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicketHistoryByUser", ReplyAction="http://tempuri.org/IService1/GetTicketHistoryByUserResponse")]
        AdminClient.QueueServiceRef.QueueTicket[] GetTicketHistoryByUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTicketHistoryByUser", ReplyAction="http://tempuri.org/IService1/GetTicketHistoryByUserResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket[]> GetTicketHistoryByUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CallNextTicket", ReplyAction="http://tempuri.org/IService1/CallNextTicketResponse")]
        void CallNextTicket(int branchId, int serviceId, int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CallNextTicket", ReplyAction="http://tempuri.org/IService1/CallNextTicketResponse")]
        System.Threading.Tasks.Task CallNextTicketAsync(int branchId, int serviceId, int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SkipTicket", ReplyAction="http://tempuri.org/IService1/SkipTicketResponse")]
        void SkipTicket(int ticketId, int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SkipTicket", ReplyAction="http://tempuri.org/IService1/SkipTicketResponse")]
        System.Threading.Tasks.Task SkipTicketAsync(int ticketId, int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CloseTicket", ReplyAction="http://tempuri.org/IService1/CloseTicketResponse")]
        void CloseTicket(int ticketId, int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CloseTicket", ReplyAction="http://tempuri.org/IService1/CloseTicketResponse")]
        System.Threading.Tasks.Task CloseTicketAsync(int ticketId, int adminId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLogs", ReplyAction="http://tempuri.org/IService1/GetAllLogsResponse")]
        AdminClient.QueueServiceRef.CallLog[] GetAllLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllLogs", ReplyAction="http://tempuri.org/IService1/GetAllLogsResponse")]
        System.Threading.Tasks.Task<AdminClient.QueueServiceRef.CallLog[]> GetAllLogsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AdminClient.QueueServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AdminClient.QueueServiceRef.IService1>, AdminClient.QueueServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AdminClient.QueueServiceRef.User Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.User> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void Register(AdminClient.QueueServiceRef.User u) {
            base.Channel.Register(u);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(AdminClient.QueueServiceRef.User u) {
            return base.Channel.RegisterAsync(u);
        }
        
        public AdminClient.QueueServiceRef.Branch[] GetAllBranches() {
            return base.Channel.GetAllBranches();
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.Branch[]> GetAllBranchesAsync() {
            return base.Channel.GetAllBranchesAsync();
        }
        
        public void AddBranch(AdminClient.QueueServiceRef.Branch b) {
            base.Channel.AddBranch(b);
        }
        
        public System.Threading.Tasks.Task AddBranchAsync(AdminClient.QueueServiceRef.Branch b) {
            return base.Channel.AddBranchAsync(b);
        }
        
        public void UpdateBranch(AdminClient.QueueServiceRef.Branch b) {
            base.Channel.UpdateBranch(b);
        }
        
        public System.Threading.Tasks.Task UpdateBranchAsync(AdminClient.QueueServiceRef.Branch b) {
            return base.Channel.UpdateBranchAsync(b);
        }
        
        public void DeleteBranch(int branchId) {
            base.Channel.DeleteBranch(branchId);
        }
        
        public System.Threading.Tasks.Task DeleteBranchAsync(int branchId) {
            return base.Channel.DeleteBranchAsync(branchId);
        }
        
        public AdminClient.QueueServiceRef.Service[] GetAllServices() {
            return base.Channel.GetAllServices();
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.Service[]> GetAllServicesAsync() {
            return base.Channel.GetAllServicesAsync();
        }
        
        public AdminClient.QueueServiceRef.Service[] GetServicesByBranch(int branchId) {
            return base.Channel.GetServicesByBranch(branchId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.Service[]> GetServicesByBranchAsync(int branchId) {
            return base.Channel.GetServicesByBranchAsync(branchId);
        }
        
        public void AddService(AdminClient.QueueServiceRef.Service s) {
            base.Channel.AddService(s);
        }
        
        public System.Threading.Tasks.Task AddServiceAsync(AdminClient.QueueServiceRef.Service s) {
            return base.Channel.AddServiceAsync(s);
        }
        
        public void UpdateService(AdminClient.QueueServiceRef.Service s) {
            base.Channel.UpdateService(s);
        }
        
        public System.Threading.Tasks.Task UpdateServiceAsync(AdminClient.QueueServiceRef.Service s) {
            return base.Channel.UpdateServiceAsync(s);
        }
        
        public void DeleteService(int serviceId) {
            base.Channel.DeleteService(serviceId);
        }
        
        public System.Threading.Tasks.Task DeleteServiceAsync(int serviceId) {
            return base.Channel.DeleteServiceAsync(serviceId);
        }
        
        public AdminClient.QueueServiceRef.User[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.User[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public AdminClient.QueueServiceRef.User GetUserById(int userId) {
            return base.Channel.GetUserById(userId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.User> GetUserByIdAsync(int userId) {
            return base.Channel.GetUserByIdAsync(userId);
        }
        
        public void AddUser(AdminClient.QueueServiceRef.User u) {
            base.Channel.AddUser(u);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(AdminClient.QueueServiceRef.User u) {
            return base.Channel.AddUserAsync(u);
        }
        
        public void UpdateUser(AdminClient.QueueServiceRef.User u) {
            base.Channel.UpdateUser(u);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(AdminClient.QueueServiceRef.User u) {
            return base.Channel.UpdateUserAsync(u);
        }
        
        public void DeleteUser(int userId) {
            base.Channel.DeleteUser(userId);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(int userId) {
            return base.Channel.DeleteUserAsync(userId);
        }
        
        public AdminClient.QueueServiceRef.QueueTicket TakeTicket(int userId, int serviceId, int branchId) {
            return base.Channel.TakeTicket(userId, serviceId, branchId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket> TakeTicketAsync(int userId, int serviceId, int branchId) {
            return base.Channel.TakeTicketAsync(userId, serviceId, branchId);
        }
        
        public AdminClient.QueueServiceRef.QueueTicket GetActiveTicketByUser(int userId) {
            return base.Channel.GetActiveTicketByUser(userId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket> GetActiveTicketByUserAsync(int userId) {
            return base.Channel.GetActiveTicketByUserAsync(userId);
        }
        
        public AdminClient.QueueServiceRef.QueueTicket[] GetTicketsByBranch(int branchId) {
            return base.Channel.GetTicketsByBranch(branchId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket[]> GetTicketsByBranchAsync(int branchId) {
            return base.Channel.GetTicketsByBranchAsync(branchId);
        }
        
        public AdminClient.QueueServiceRef.QueueTicket[] GetWaitingTickets(int branchId, int serviceId) {
            return base.Channel.GetWaitingTickets(branchId, serviceId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket[]> GetWaitingTicketsAsync(int branchId, int serviceId) {
            return base.Channel.GetWaitingTicketsAsync(branchId, serviceId);
        }
        
        public int GetPositionInQueue(int ticketId, int branchId, int serviceId) {
            return base.Channel.GetPositionInQueue(ticketId, branchId, serviceId);
        }
        
        public System.Threading.Tasks.Task<int> GetPositionInQueueAsync(int ticketId, int branchId, int serviceId) {
            return base.Channel.GetPositionInQueueAsync(ticketId, branchId, serviceId);
        }
        
        public AdminClient.QueueServiceRef.QueueTicket[] GetTicketHistoryByUser(int userId) {
            return base.Channel.GetTicketHistoryByUser(userId);
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.QueueTicket[]> GetTicketHistoryByUserAsync(int userId) {
            return base.Channel.GetTicketHistoryByUserAsync(userId);
        }
        
        public void CallNextTicket(int branchId, int serviceId, int adminId) {
            base.Channel.CallNextTicket(branchId, serviceId, adminId);
        }
        
        public System.Threading.Tasks.Task CallNextTicketAsync(int branchId, int serviceId, int adminId) {
            return base.Channel.CallNextTicketAsync(branchId, serviceId, adminId);
        }
        
        public void SkipTicket(int ticketId, int adminId) {
            base.Channel.SkipTicket(ticketId, adminId);
        }
        
        public System.Threading.Tasks.Task SkipTicketAsync(int ticketId, int adminId) {
            return base.Channel.SkipTicketAsync(ticketId, adminId);
        }
        
        public void CloseTicket(int ticketId, int adminId) {
            base.Channel.CloseTicket(ticketId, adminId);
        }
        
        public System.Threading.Tasks.Task CloseTicketAsync(int ticketId, int adminId) {
            return base.Channel.CloseTicketAsync(ticketId, adminId);
        }
        
        public AdminClient.QueueServiceRef.CallLog[] GetAllLogs() {
            return base.Channel.GetAllLogs();
        }
        
        public System.Threading.Tasks.Task<AdminClient.QueueServiceRef.CallLog[]> GetAllLogsAsync() {
            return base.Channel.GetAllLogsAsync();
        }
    }
}
